version: '3.8'
services:
  envoy:
    build:
      context: ./server
      dockerfile: envoy.Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - grpc
  grpc:
    build:
      context: ./server
      dockerfile: grpc.Dockerfile
    volumes:
      - ./server/server.js:/app/server.js
  front:
    build:
      context: ./front
    entrypoint: ./scripts/docker-entrypoint.sh
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ./front:/app/
      - ./server/helloworld.proto:/server/helloworld.proto
    depends_on:
      - envoy
